import type { Metadata } from "next";
import "./globals.css";
import { SideBar } from "./components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>

        <div className="w-full h-screen  overflow-hidden grid grid-cols-[13rem_1fr] gap-3.5">

          <aside className="overflow-y-auto">
            <div className="w-full h-max">
              <SideBar />
            </div>
          </aside>

          <main className="bg-myBlue/5">
            {children}
          </main>

        </div>

      </body>
    </html>
  );
}
