import type { Metadata } from "next";
import "./globals.css";
import { SideBar } from "./components";
import ChatsContextProvider from "./components/chat/context/ChatsContextProvider";
import "@mantine/core/styles.css"
import { MantineProvider, createTheme } from "@mantine/core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: "vazir"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <ChatsContextProvider>

        <body>
          <MantineProvider theme={theme}>
            <div className="w-full h-screen  overflow-hidden grid grid-cols-1 lg:grid-cols-[14rem_1fr] bg-myBlue/10 ">

              <aside className="overflow-y-auto max-lg:hidden">
                <div className="w-full">
                  <SideBar />
                </div>
              </aside>

              <main className="overflow-y-auto">
                {children}
              </main>

            </div>
          </MantineProvider>
        </body>

      </ChatsContextProvider>
    </html >
  );
}
