import type { Metadata } from "next";
import "./globals.css";
import { SideBar } from "./components";
import TopNavigationBar from "./components/TopNavigationBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>

        <div className="w-full h-screen  overflow-hidden grid grid-cols-1 lg:grid-cols-[14rem_1fr]">

          <aside className="overflow-y-auto max-lg:hidden">
            <div className="w-full">
              <SideBar />
            </div>
          </aside>

          <main className="bg-myBlue/10 overflow-y-auto">
            {children}
          </main>

        </div>

      </body>
    </html>
  );
}
